# Exercícios 

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>

In [2]:
import numpy as np

In [4]:
array = np.array([1,2,3,4,5,6,7,8,9])
array[array%2==1]

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [5]:
np.where(array%2==1, 0, array)

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [7]:
file = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter = ',', usecols = [0,1,2,3])
file_10 = file[0:10]
file_10

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [9]:
media = file[:,0].mean()
mediana = np.median(file[:,0])
desvio = file[:, 0].std()

print(f'Média = {media:.2f}')
print(f'Mediana = {mediana}')
print(f'Devio padrão = {desvio:.2f}')

Média = 5.84
Mediana = 5.8
Devio padrão = 0.83


5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [10]:
file[(file[:,2]>1.5) & (file[:,0]<5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

6 - Esse dataset possui nans?

In [11]:
np.isnan(file).sum()

0

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [12]:
volume = (np.pi*file_10[:,2]*(file_10[:,0]**2))/3
volume

array([38.13265163, 35.20049849, 30.07237208, 33.23805027, 36.65191429,
       51.91167701, 31.02218026, 39.26990817, 28.38324243, 37.71481981])